service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dotenv-plugin

package:
  include:
    - config/.env.dev

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: user
          method: post
  verifyOtp:
    handler: app/handler.verifyOTP
    events:
      - http:
          path: verifyOtp
          method: post
  profileUpdate:
    handler: app/handler.updateProfile
    events:
      - http:
          path: profileUpdate
          method: put
 